### ISSUE TITLE
Storage functionality missing

### ISSUE THREAD

**Issue by r00t-us3r** [supabase-community/supabase-on-aws#11]
# Bug report

## Describe the bug

When Studio is opened, the "Storage" section on the dashboard is missing.
When trying to access the storage page using the direct url (as taken from local running copy) - it redirect straight back to the dashboard, temporarily displaying "Buckets" in the tab title.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Launch the stack
2. Open studio url
3. Storage is missing from side navigation

## Expected behavior

See storage tab which gives abilities to "Create Buckets"

## Screenshots

**Missing tab on CloudFormation stack**
![Screen Shot 2022-12-27 at 15 38 30](https://user-images.githubusercontent.com/45609059/209688782-0a7d6962-2202-4577-b42a-aa8bea8e3ea9.png)

**Present on docker-compose local install**
![Screen Shot 2022-12-27 at 15 38 59](https://user-images.githubusercontent.com/45609059/209688904-d51f3bb6-b245-4dc6-9c89-45cbd2134061.png)

**Storage Service Running in ECS Cluster**
![Screen Shot 2022-12-27 at 15 41 07](https://user-images.githubusercontent.com/45609059/209689095-114c2549-84fc-4e3e-8993-4ef366da5b3b.png)
![Screen Shot 2022-12-27 at 15 41 00](https://user-images.githubusercontent.com/45609059/209689107-4db5fe89-d38e-4102-84de-d34989c720b5.png)

**Comment by umuthopeyildirim** [comment]
Is there any update on this?

**Comment by mats16** [comment]
This is not a bug, just the latest version of Studio has not been deployed.

Lates template support new Studio, please try it.
