### ISSUE TITLE
Connecting to Studio

### ISSUE THREAD

**Issue by gridworkz** [supabase-community/supabase-on-aws#13]
Noobie here. I just spun up a fresh Supabase stack on AWS. How do I connect to Studio? I notice it creates a loadbalancer on AWS so I pointed a CNAME record to it but didn't get any response. Any pointers appreciated. Cheers, Dave

**Comment by mats16** [comment]
Hi @gridworkz !

Studio is hosted on Amplify Hosting. Please check it.
