### ISSUE TITLE
Excessive CloudWatch Usage

### ISSUE THREAD

**Issue by umuthopeyildirim** [supabase-community/supabase-on-aws#58]
# Bug report

## Describe the bug

 I wanted to bring to your attention an issue I have encountered with CloudWatch costs after starting supabase-on-aws. I believe the costs have become excessive, averaging more than $2.50 per day over the span of two months.

## To Reproduce

Just use this repo.

## Expected behavior

The exact cause of this increase is currently unknown to me. I wanted to reach out to other users to confirm if they have experienced similar cost spikes.

## Screenshots
![Screenshot 2023-07-11 at 1 28 51 AM](https://github.com/supabase-community/supabase-on-aws/assets/39514133/65611b3a-43e8-42b8-b4ee-25e8b64a928c)
[costs.csv](https://github.com/supabase-community/supabase-on-aws/files/12009004/costs.csv)

**Comment by mats16** [comment]
Thanks!

Cloud you tell me more details?
Please send a bills.

such as 👇 
<img width="1456" alt="スクリーンショット 2023-07-13 15 59 00" src="https://github.com/supabase-community/supabase-on-aws/assets/5158858/b90b2d38-0446-4745-9f1f-373511b8b818">

**Comment by umuthopeyildirim** [comment]
Hi!
I'm not a AWS Expert so thanks for the help. I added pdf's of billings.

[Billing Management Console - July.pdf](https://github.com/supabase-community/supabase-on-aws/files/12036741/Billing.Management.Console.-.July.pdf)
[Billing Management Console - June.pdf](https://github.com/supabase-community/supabase-on-aws/files/12036742/Billing.Management.Console.-.June.pdf)

**Comment by umuthopeyildirim** [comment]
After checking that page you suggested it seems like Datadog is causing this problem. I removed it from AWS. I will close this issue for now and wait for a couple day to check if that would fix it.  
Thanks for the help!

**Comment by mats16** [comment]
@umuthopeyildirim Thanks!

Account ID is not masked for July.pdf.
Can you delete it?
