### ISSUE TITLE
Template for ap-south-1 region

### ISSUE THREAD

**Issue by yogeshbeniwal** [supabase-community/supabase-on-aws#60]
# Feature request

## Is your feature request related to a problem? Please describe.

Create template to use for ap-south-1 (Mumbai) Region

## Describe the solution you'd like

Add ap-south-1 (Mumbai) as one of Region to launch stack

![Screenshot](https://github.com/supabase-community/supabase-on-aws/assets/7325107/4877156c-8ee0-4624-bb13-733611807170)

**Comment by mats16** [comment]
@yogeshbeniwal 
Now, the template for ap-south-1 is available!
Please check it.
