### ISSUE TITLE
Realtime WebSocket connection fails

### ISSUE THREAD

**Issue by salmoro** [supabase-community/supabase-on-aws#66]
# Bug report

## Describe the bug
All works well other than realtime pg connection. browser throws the following
![Screenshot 2023-07-31 at 6 50 18 PM](https://github.com/supabase-community/supabase-on-aws/assets/20197680/a24966fa-712d-4bd9-a007-5c4c1d3796a5)

When I look on AWS ECS on the RealtimeService logs I see a lot of 
```
project=realtime external_id=realtime [error] Auth error: tenant `realtime` not found`
```
When I look at the `realtime.tenants` table I only see one entry and the name is `realtime-dev` so I suspect this is the issue.

If this is the issue, what's a good way to solve this other than editing this field directly in the DB?

**Comment by mats16** [comment]
https://github.com/supabase/realtime/tree/main#server-setup

`realtime-dev` may be the default tenant.
You need to use the default tenant or create a new tenant.
Can you try it?

**Comment by mats16** [comment]
@salmoro `realtime-dev` may be the default tenant.
https://github.com/supabase/realtime/tree/main#server-setup

You need to use the default tenant or create a new tenant.
Can you try it?

**Comment by salmoro** [comment]
@mats16 I'm having a hard time figuring this out. is this supposed to work out of the box?

**Comment by mats16** [comment]
@salmoro Sorry, I have identified the cause of the problem.

The subdomain of supabase-realtime is used to determine tenat_id.
The domain name must be set to something like `realtime-dev.supabase.internal`.

I already fix it on latest version. Please use it.
