### ISSUE TITLE
How to lock down studio?

### ISSUE THREAD

**Issue by keeganmccallum** [supabase-community/supabase-on-aws#70]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

By default, studio launched unauthed and exposed to the open web, how can I configure github sso?

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by umuthopeyildirim** [comment]
Hello @keeganmccallum

To implement password protection for your Supabase Studio, follow these steps within AWS Amplify:

1. Access your Supabase Studio through AWS Amplify.
2. Inside the App Settings, locate the 'Access control' section.
3. Toggle the 'Apply a global password' option to 'ON'.
4. Set your desired password for the Supabase Studio access.

By applying this password protection, your Supabase Studio will remain accessible on the open web, but only authorized users with the correct password will be able to access it. I plan to contribute to the documentation by creating a pull request that includes these instructions.

**Comment by mats16** [comment]
The method for setting the password on the Amplify Hosting side is as described above.

Another option is to set up an authentication backend in Supabase Studio.
My research shows that Studio of Supabase Cloud uses another GoTrue for authentication.

**Comment by mats16** [comment]
Closing this as stale -- please re-open if you still have issues!
