### ISSUE TITLE
Deployment fails with error: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400

### ISSUE THREAD

**Issue by tolikkostin** [supabase-community/supabase-on-aws#83]
# Bug report

## Describe the bug

Deployment fails with error: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400

``` console
Supabase: creating CloudFormation changeset...
9:23:28 AM | CREATE_FAILED        | AWS::Lambda::Function                         | StudioRepositoryImportFunctionF87C7D62
Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 419ca9ff-069e-4915-83d3-fdbecfbf06ad)" (RequestToken: 5b39077e-76e
3-3c3d-714e-7ead45d97aff, HandlerErrorCode: InvalidRequest)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

``` console
git clone https://github.com/mats16/supabase-on-aws.git
cd supabase-on-aws
yarn install
cdk bootstrap
cdk deploy Supabase
```

## Expected behavior

Succesful supabase installation.

## Screenshots

![Screenshot 2023-11-22 at 09 27 19](https://github.com/supabase-community/supabase-on-aws/assets/26538478/7ba34f40-c85a-4822-8aa8-1b12c3119240)

## System information

- OS: macOS 14.1
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Seems that error in this [line](https://github.com/supabase-community/supabase-on-aws/blob/b6273dd1a00a183ec4771abc70f805076c365f2a/src/supabase-studio/index.ts#L211). If I specify `3008` the deployment works.

**Comment by mats16** [comment]
Thanks for the report.

I am aware of this issue and am currently addressing it.

**Comment by mats16** [comment]
@tolikkostin  Thank you for your reporting.

This issue seems to be dependent on your AWS account.
https://stackoverflow.com/questions/70943739/aws-lambda-memorysize-value-failed-to-satisfy-constraint

Could you please contact AWS Support?

**Comment by tolikkostin** [comment]
@mats16 Thanks, got it.
